### PR TITLE
Invoke getMixinSetupClass method on coremods if they have it

### PR DESCRIPTION
**Pull request by embeddedt**
This is related to our discussion in #12. Not sure if it's a 100% perfect solution, or if it works properly with mods in dev environments, but it seems to work in production just fine.

With this approach, implementing vanilla mixins is now very clean: one method in the `IFMLLoadingPlugin` [here](https://github.com/embeddedt/phosphor-forge112/blob/5ef09eb4cf7780b36fcc88303eac2e1d96c5d808/src/main/java/me/jellysquid/mods/phosphor/core/PhosphorFMLLoadingPlugin.java#L39-L41), and a standard setup hook [here](https://github.com/embeddedt/phosphor-forge112/blob/1.12.x/dynamiclights/src/main/java/me/jellysquid/mods/phosphor/core/PhosphorFMLSetupHook.java). This also allows the mod to load normally when MixinBooter isn't installed.

What do you think?

### CODE REVIEW

**Comment by Rongmario** [comment]
Thanks for the PR, you've inspired me to come up with something of my own. We'll compare and see which is more suitable.

**Comment by Rongmario** [comment]
After some consideration, is there an advantage of MixinBooter providing anything for implementing vanilla/forge mixins? After all, calling `MixinBootstrap.init()`  `Mixins.addConfiguration`... is all you do. And Forge cannot really enforce dependencies, soft or hard, when loading coremods, for some reason `@IFMLLoadingPlugin.DependsOn` is just unimplemented and useless.

**Comment by embeddedt** [comment]
> After all, calling MixinBootstrap.init() Mixins.addConfiguration... is all you do.

The idea is to avoid shading Mixin into each mod. To do that there needs to be a mod providing Mixin. There then comes the issue of checking whether that mod is actually installed and available. Technically using `Class.forName` and then checking for a `ClassNotFoundException` works, but it's not the most ideal.

**Comment by Rongmario** [comment]
@embeddedt take a look at the `support-early-mixins` branch: https://github.com/LoliKingdom/MixinBooter/tree/support-early-mixins

**Comment by embeddedt** [comment]
It works well with one minor change (added to this PR). This is even cleaner than how I did it; good idea!

**Comment by Rongmario** [comment]
Thanks! That rounds it up, I'll get it ready for next release.

**Pull request merged**
